const constants = {
  WINDOW_RESIZE: 'WINDOW_RESIZE',
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  SET_USER_DATA: 'SET_USER_DATA',
  PRODUCTS_DATA_FILE_LOADED: 'PRODUCTS_DATA_FILE_LOADED',
  LOADING_DATA_FILE: 'LOADING_DATA_FILE',
  LOADING_DATA_FILE_FINISHED: 'LOADING_DATA_FILE_FINISHED',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT'
}

export default constants
